name: log
version: 0.0.1

homepage: https://github.com/renggli/dart-log
description: A logging library for Dart.

environment:
  sdk: ^3.2.0
dependencies:
  more: ^4.0.1
  meta: ^1.9.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
