name: log
version: 0.0.1

homepage: https://github.com/renggli/dart-log
description: A logging library for Dart.

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  more: ^3.8.0
  meta: ^1.7.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
